sudo: required
services: 
  - docker


before_install:
  - docker build -t ganzaaristide/docker-react -f Dockerfile.dev .


script:
  - docker run ganzaaristide/docker-react npm run test -- --coverage


# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: docker-react
#   env: "Docker-env"
#   bucket_name: "bucket name"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$$AWS_SECRET_KEY"


