sudo: required
services: 
  - docker


before_install:
  - docker build -t ganzaaristide/docker-react -f Dockerfile.dev .


script:
  - docker run ganzaaristide/docker-react npm run test -- --coverage
